### ISSUE TITLE
Publish Docker image?

### ISSUE THREAD

**Issue by MPV** [leprechaun/gocd-prometheus-exporter#2]
Great project!

Up for publishing the Docker image somewhere?

Example for Github to Docker Hub automated publishing:
https://docs.docker.com/docker-hub/github/

**Comment by leprechaun** [comment]
Thanks! Very much a work in progress. The numbers don't quite express what you'd expect them to due to over simplicity. So, don't bother running it at this point ... but it's it's already on docker hub, if you really care to :) [here is is](https://hub.docker.com/r/leprechaun/gocd-prometheus-exporter/builds/)

**Comment by MPV** [comment]
Ooh, nice! Will close this issue then. 😊
