### ISSUE TITLE
important CD stats

### ISSUE THREAD

**Issue by pracplayopen** [leprechaun/gocd-prometheus-exporter#3]
Great project.

here largely see CD about keeping green pipelines.

your project is great at tracking build times and bottlenecks, very important to iteration.

Is it missing broken pipeline/stage status?  tracking this over time is also important for iteration cause it siginifies process shortcomings.

was looking for something like:

```
pipeline_somepipeline_errors 0 GAUGE
pipeline_B_errors 0 GAUGE
pipeline_C_errors 2 GAUGE
stage_somepipeline_somestage_errors 0 GAUGE
...
```
there's probably other ways to go about it as well.

maybe outside your intent but you requested feedback so that was the impression here.

**Comment by leprechaun** [comment]
Thanks for the feedback!

I'm not sure what you're asking for, though. More, precisely, what do you mean by "errors"? Both pipeline (instance) and stage failures are a binary thing, either pass or fail.

I'm thinking one "error" is a *job failure*. A stage has one or more jobs, which can all pass or fail independently. AFAIK, that's the only type of failure that doesn't lead to immediate failure/quitting.

If that's what you meant, then sure, it very much sounds like something worth tracking! If I misunderstood, then please correct me :)

Are you OK with using labels instead of distinct metrics, eg 'gocd_stage_job_error_count' with labels [pipeline_group, pipeline, stage]?

**Comment by pracplayopen** [comment]
yes you're right there should only be able to be one pipeline error at any given time in most situations, so that sounds right.

the reason we suggested multiple metrics for each pipeline is bc the recommended practices are not to use labels for unbounded metrics because of dimensionality:  https://prometheus.io/docs/practices/naming/

```
Do not use labels to store dimensions with high cardinality (many different label values) or other unbounded sets of values.
```

I suppose using one metric with many labels does simplify metric aggregation, so not sure which is worse tradeoff on average.    We presently have 50+ pipelines, could easily get many multiples of this and i'm quite sure there are many way ahead of us (since pipeline chaining is one of big advantages of gocd).

Your 'latest' metric is interesting, will look into that.

**Comment by leprechaun** [comment]
Yeah, cardinality is something I was aware of. I went with ease of templating and aggregation instead, for the time being. Putting in build numbers would have been tempting, but that's where I drew the line.

That being said, I haven't run Prometheus at  scale, yet. Hopefully this won't come back and bite me.

**Comment by pracplayopen** [comment]
labels are powerful and your trade is valuable in many situations esp around t0.

if things scale you can always make configurable, people can fork and repopulate or reimport data, so no biggie.

we're going to close this issue as it seems current version addressed our comments.

haven't had a chance to try it yet.     

thanks again for your efforts here!
